baseURL = "https://me.kqh.me/"
languageCode = "zh-HK"
title = "柯棋瀚主頁"
enableRobotsTXT = true
theme = "CJK"
disablePathToLower = true
hasCJKLanguage = true
uglyURLs = false
rssLimit = 20

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
    tabWidth = 4
    
[taxonomies]
author = "author"
tag = "tag"
category = "category"
series = "series"
note = "note"
location = "location"
tutokind = "tutokind"
book = "book"
examkind = "examkind"
datakind = "datakind"

[author] # essential
name = "柯棋瀚"

[sitemap] # essential
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[params]
version = "4.33"
# 非隱藏板塊
Sections1 = [
  "post",
  "pin",
  "exam",
  "gallery",
  "net",
  "read",
  "key",
  "database",
  "column1",
]
# 參與統計的板塊
Sections2 = [
  "post",
  "pin",
  "exam",
  "net",
  "read",
  "key",
  "database",
  "column1",
]
# 上面的排除掉pin,gallery
Sections3 = [
  "post",
  "exam",
  "net",
  "read",
  "key",
  "database",
  "column1"
]

copyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a>，非商業用途可隨意使用'
vertical = true
summaries = false # Set to true to show summaries of posts on homepage
divider = false #\a0 Set to false to remove divider below posts on homepage
schema = false # Set to true to add Schema.org metadata
opengraph = false # Set to true to add Open Graph metadata
twittercards = false # Set to true to add Twitter Cards metadata
repository = "https://github.com/kujihhoe/HUGO-Theme-CJK/blob/master/content/"
