baseURL = "https://me.kqh.me/"
languageCode = "zh-HK"
title = "柯棋瀚主頁"
enableRobotsTXT = true
theme = "CJK"
disablePathToLower = true
hasCJKLanguage = true
uglyURLs = false
rssLimit = 20

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
    tabWidth = 4
    
[taxonomies]
author = "author"
tag = "tag"
category = "category"
series = "series"
note = "note"
location = "location"
tutokind = "tutokind"
book = "book"
examkind = "examkind"
datakind = "datakind"

[author] # essential
name = "柯棋瀚"

[sitemap] # essential
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[related]
  includeNewer = true
  threshold = 100
  toLower = true
[[related.indices]]
  name = 'series'
  weight = 100
[[related.indices]]
  name = 'category'
  weight = 80
[[related.indices]]
  name = 'tag'
  weight = 41
[[related.indices]]
  name = 'location'
  weight = 41
[[related.indices]]
  name = 'note'
  weight = 31
[[related.indices]]
  name = 'author'
  weight = 21  

[[menu.nav]]
name = "赫赫文王"
weight = 1
url = "/"

[[menu.nav]]
name = "文王在天"
weight = 2
url = "/dingsi"

[[menu.nav1]]
name = "發現"
weight = 13
url = "/#discover"

[[menu.nav1]]
name = "歸檔"
weight = 14
url = "/post"

[[menu.nav2]]
name = "赫赫蠹書"
weight = 31
url = "/read"

[[menu.nav2]]
name = "赫赫金鑰"
weight = 32
url = "/key"

[[menu.nav2]]
name = "資源資料"
weight = 33
url = "/database"

[[menu.nav2]]
name = "考試筆記"
weight = 34
url = "/exam"

[[menu.nav3]]
name = "刷微博"
weight = 21
url = "/newsletter"

[[menu.nav3]]
name = "史網"
weight = 24
url = "/nethistory"

[[menu.nav4]]
name = "雲遊博物"
weight = 40
url = "/column1"

[[menu.nav5]]
name = "個人主頁"
weight = 50
url = "https://me.kqh.me"

[[menu.nav5]]
name = "赫赫曆藏"
weight = 52
url = "https://cal.kqh.me"

[[menu.nav5]]
name = "琴衡"
weight = 53
url = "https://qin.kqh.me"

[[menu.nav5]]
name = "情形於聲"
weight = 54
url = "https://thefaint.cc"

[[menu.nav5]]
name = "淘寶商店"
weight = 55
url = "https://m.tb.cn/h.fQv7iYb?sm=b1c19c"

[[menu.nav5]]
name = "春秋學刊"
weight = 56
url = "https://chunqiu.kqh.me"

[params]
version = "4.33"
# 非隱藏板塊
Sections1 = [
  "post",
  "pin",
  "exam",
  "gallery",
  "net",
  "read",
  "key",
  "database",
  "column1",
]
# 參與統計的板塊
Sections2 = [
  "post",
  "pin",
  "exam",
  "net",
  "read",
  "key",
  "database",
  "column1",
]
# 上面的排除掉pin,gallery
Sections3 = [
  "post",
  "exam",
  "net",
  "read",
  "key",
  "database",
  "column1"
]
# 上面的排除掉post
Sections4 = [
  "exam",
  "net",
  "read",
  "key",
  "database",
  "column1"
]

copyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a>，非商業用途可隨意使用'
vertical = true
summaries = false # Set to true to show summaries of posts on homepage
divider = false #\a0 Set to false to remove divider below posts on homepage
schema = false # Set to true to add Schema.org metadata
opengraph = false # Set to true to add Open Graph metadata
twittercards = false # Set to true to add Twitter Cards metadata
repository = "https://github.com/kujihhoe/HUGO-Theme-CJK/blob/master/content/"
